### ISSUE TITLE
CloudFront CDN support for Open Datasets

### ISSUE THREAD

**Issue by devanshk** [awslabs/open-data-registry#1282]
Not sure if this is the right spot to ask, but does Open Data allow dataset owners to use CDNs for download and delivery?

Asking because S3 has notoriously low performance in regions like China, which makes multi-TB datasets impossible to download - but CDNs in that region would be much faster.

**Comment by jflasher** [comment]
Hi @devanshk, dataset providers (or anyone else!) can definitely put a CDN in front of the data being made available via S3. Since the majority of the buckets are openly available, anyone can run a CDN for public (or their own) use, at their own expense. For datasets being sponsored via https://opendata.aws/odp, we generally do not cover the costs of a CDN via the program (though they can still be paid for by others), but we are open to exploring exceptions on a case by case basis.
