### ISSUE TITLE
Planetary Data Sets - New Tag?

### ISSUE THREAD

**Issue by jlaura** [awslabs/open-data-registry#1582]
A brief browse of the yaml data set files and the tags.yaml suggests that #1580 might be the first PR for a non-earth centric data set. This data set is the first of many planetary analysis ready data sets that NASA has collected and/or processed. Most of the earth-centric tags are terrific, such as satellite imagery and describe the data well.

Does it make sense to just use the existing tags, to add a generic 'not earth' tag such as 'planetary' or tag data sets based on the body that they target (e.g., moon, mars, etc.)? The last option could get unwieldy in the long term because of the [shear number](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/naif_ids.html#Planets%20and%20Satellites) of different bodies.

Much appreciate any thoughts!

**Comment by jeffejefe** [comment]
In general we tend to keep the tags fairly generic so a "planetary" tag may make sense since we have "earth observation". I wouldn't overthink our tags at this point, the provide simple ways to group like datasets e.g. https://registry.opendata.aws/tag/astronomy/ however if these are part of a larger collection of planetary or NASA they may even be suited for https://registry.opendata.aws/collab/nasa/. On that front, is USGS or NASA the Data Provider here? In other words are these coming in via the NASA Space Act Agreement or are they completely independent?

**Comment by jeffejefe** [comment]
tag has been added thanks @jlaura
