### ISSUE TITLE
Download speed fluctuations 

### ISSUE THREAD

**Issue by giorgiobasile** [awslabs/open-data-registry#1999]
Hi, I'm working with the [Sentinel-2 Cloud-Optimized GeoTIFFs](https://registry.opendata.aws/sentinel-2-l2a-cogs/) dataset, and from time to time, I'm experiencing some important fluctuations in terms of download speed.
Download speed is usually in the order of 15 MB/s, but there are situations where it drops to 100-200 KB/s for several hours, and I'm not sure it is due to some security settings of the corporate infrastructure I'm using or some throttling applied by AWS. 

Is there any such throttling applied by AWS on these buckets - especially when no AWS credentials are supplied and requests come from outside the AWS infrastructure?

**Comment by pschmied** [comment]
Hi @giorgiobasile , under normal circumstances, there would be no throttle applied to downloads from S3. Depending on where you are accessing the data from, and what method you are using to access the data, there are a variety of reasons why you might see download speeds vary.

Two things to try: 1. if you're running your workload in AWS, double check that you're accessing the data from the same region as the S3 bucket (us-west-2). 2. if you are using e.g. the AWS CLI to access these data, you may want to consider whether the default configuration is ideal for your workload. If transferring the data within AWS or on an otherwise reliable network link, increasing the maximum chunk size parameter can often improve things due to reduced number of requests per volume of data: https://docs.aws.amazon.com/cli/latest/topic/s3-config.html

Please feel free to reopen if neither of these suggestions help.
