### ISSUE TITLE
Managed by links for UniProt do not render as expected.

### ISSUE THREAD

**Issue by JervenBolleman** [awslabs/open-data-registry#983]
On the page https://registry.opendata.aws/uniprot/ the managed by section does not render as I expected. What is the correct syntax? I currently have

```yaml
ManagedBy: "[SIB Swiss Institute of Bioinformatics](https://sp.sib.swiss/) on behalf of the [UniProt Consortium](https://www.uniprot.org/help/about)"
```

**Comment by jflasher** [comment]
Hi @JervenBolleman, I think this is actually nothing you can control, it's likely due to the Markdown being included programmatically in the template. I've opened up https://github.com/awslabs/open-data-registry-browser/issues/190 and will take a look. Closing this issue since it's captured elsewhere. Thanks for reporting!

**Comment by jflasher** [comment]
Looking into this a bit more, we actually do account for the presence of Markdown, but we only handle a single Markdown entity (the first name/url basically) so this double name/url pair fails the parsing. @JervenBolleman as the logic for this is already somewhat complex, would you be able to recast your `ManagedBy` to a single url link like below?

`ManagedBy: "[SIB Swiss Institute of Bioinformatics](https://sp.sib.swiss/) on behalf of the UniProt Consortium."`

UniProt is already linked in the description, so hopefully that's not a problem? Thanks!
